server:
  port: 8011
  servlet:
    context-path: /

spring:
  application:
    name: wms-account
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/train_db?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # Druid数据源配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    cluster:
      nodes:
        - 192.168.56.10:7001
        - 192.168.56.10:7002
        - 192.168.56.11:7001
        - 192.168.56.11:7002
        - 192.168.56.12:7001
        - 192.168.56.12:7002
      max-redirects: 3 # 失败最大的重定向次数
    password: 123456
    timeout: 60000
    lettuce:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8  #连接池最大连接数（使用负值表示没有限制）
        time-between-eviction-runs:

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.zhanghh.wms.account.entity

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

#配置alpha-server地址
alpha:
  cluster:
    address: 127.0.0.1:8080
omega:
  enabled: true
